### ISSUE TITLE
line drawing broken in html5? :S

### ISSUE THREAD

**Issue by increpare** [TerryCavanagh/terrylib#15]
works in flash, not in html5 (checked in chrome and safari) or neko. halp!

https://gist.github.com/increpare/aaa57e6da2dc77f8597f

**Comment by increpare** [comment]
(weird, I hacked gfx.lib a bit while working on the game, and now it magically all works -

https://gist.github.com/increpare/cc2c9422b43eb5796b11

maybe to do with the transformations? dunno! )

**Comment by TerryCavanagh** [comment]
Yeah, this is broken :/ However! You can work around it by setting the linethickness to something greater than 1.0. This works:

Gfx.setlinethickness(2);
Gfx.drawline(50, 50, 720, 200, Col.WHITE);

Will look into it!
