### ISSUE TITLE
is it confusing that some hex colors have 6 vs 8 digits?

### ISSUE THREAD

**Issue by increpare** [TerryCavanagh/terrylib#16]
I don't know what the distinction/importance of this is, or if I can use either rgb or argb anywhere. Thought I'd just mention that it's something I don't understand (but it hasn't been a problem).

**Comment by TerryCavanagh** [comment]
Yeah, I don't think I actually need ARGB values anywhere now. (ideally beginners should never see hex colours anyway). Will go through the library and make sure they're all RGB format.
