### ISSUE TITLE
drawlib tidy

### ISSUE THREAD

**Issue by increpare** [TerryCavanagh/terrylib#17]
is there a reason you do so many translates rather than using moveto/drawto in your code?

	
	public static function drawline(x1:Float, y1:Float, x2:Float, y2:Float, col:Int, alpha:Float = 1.0):Void {
		if (skiprender && drawingtoscreen) return;
		tempshape.graphics.clear();
		tempshape.graphics.lineStyle(linethickness, col, alpha);
		tempshape.graphics.moveTo(x1,y1);
		tempshape.graphics.lineTo(x2, y2);
		drawto.draw(tempshape, shapematrix);
	}

**Comment by TerryCavanagh** [comment]
Good call!
