### ISSUE TITLE
text only prints two lines

### ISSUE THREAD

**Issue by increpare** [TerryCavanagh/terrylib#20]
why does

Text.display(Gfx.CENTER,Gfx.CENTER,"CARRIAGE GAME\nCONTROL: CLICK TO BRACE\nCLICK TO START"); 

only print the first two lines for me?

**Comment by TerryCavanagh** [comment]
Actually that shouldn't print more than one - it's kinda weird that it's
working at all! Will look into supporting newlines later!

**Comment by increpare** [comment]
heh, that explains why I had some letters clipped weirdly in one of the older games.  newline support is important for centered text - wanting to center a couple of lines of text is for me an elementary thing to want to do)

**Comment by increpare** [comment]
<3
