### ISSUE TITLE
Lots of positioning bugs in latest openfl 3.1.1 for HTML5

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/terrylib#23]

**Comment by increpare** [comment]
matrix.translate stuff/draw seem to have some problem (most easily evident in hello world)

**Comment by increpare** [comment]
found a repro case and reported it here:
http://community.openfl.org/t/bitmapdata-draw-seems-to-ignore-matrix-transform-in-html5/1825

**Comment by increpare** [comment]
fixed in the latest version.

**Comment by TerryCavanagh** [comment]
Yep, this seems to be fixed in 3.2.2!
