### ISSUE TITLE
Text.changefont() doesn't work in some situations

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/terrylib#25]
Problem is here:

```haxe
public static function changefont(t:String) {
		if(t != currentfont){
			currentfont = t;
```

currentfont seems to not be set correctly when loading fonts at init. For that matter, do I need a load font function? Couldn't I just have a changefont function? Changefont should also take size as an argument.

**Comment by increpare** [comment]
setfont might be a nicer term than changefont
