### ISSUE TITLE
look through terry's reference text for descriptions to pull to api documentation

### ISSUE THREAD

**Issue by increpare** [TerryCavanagh/terrylib#28]
https://github.com/TerryCavanagh/terrylib/blob/master/reference.txt

**Comment by TerryCavanagh** [comment]
Oh, that's started to get slightly out of date now :/

**Comment by increpare** [comment]
sure, but some of your basic comments/wording might be useful to pull :)

**Comment by increpare** [comment]
oops i totally logged this to the wrong project :P
